define({
    "lower-cambrian": "Lower Cambrian",
    "middle-cambrian": "Middle Cambrian",
    "furongian": "Furongian",
    "lower-ordovician": "Lower Ordovician",
    "middle-ordovician": "Middle Ordovician",
    "upper-ordovician": "Upper Ordovician",
    "llandovery": "Llandovery",
    "wenlock": "Wenlock",
    "ludlow": "Ludlow",
    "pridoli": "Pridoli",
    "lower-devonian": "Lower Devonian",
    "middle-devonian": "Middle Devonian",
    "upper-devonian": "Upper Devonian",
    "mississippian": "Mississippian",
    "pennsylvanian": "Pennsylvanian",
    "cisuralian": "Cisuralian",
    "guadalupian": "Guadalupian",
    "lopingian": "Lopingian",
    "lower-triassic": "Lower Triassic",
    "middle-triassic": "Middle Triassic",
    "upper-triassic": "Upper Triassic",
    "lower-jurassic": "Lower Jurassic",
    "middle-jurassic": "Middle Jurassic",
    "upper-jurassic": "Upper Jurassic",
    "lower-cretaceous": "Lower Cretaceous",
    "upper-cretaceous": "Upper Cretaceous",
    "paleocene": "Paleocene",
    "eocene": "Eocene",
    "oligocene": "Oligocene",
    "miocene": "Miocene",
    "pliocene": "Pliocene",
    "pleistocene": "Pleistocene",
    "holocene": "Holocene"
});
